name: ESP-IDF

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      matrix:
        target: [esp32, esp32s3, esp32c3]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Select configuration
      run: cp sdkconfig.defaults-${{matrix.target}} sdkconfig.defaults

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.2.2
        target: ${{matrix.target}}
        path: '.'
